### ISSUE TITLE
Plugin crashes QGIS on exit

### ISSUE THREAD

**Issue by dysteleologist** [sourcepole/qgis-instantprint-plugin#3] opened 2015-03-02 15:42 UTC
Plugin crashes QGIS (2.8.1) when closing a project that has more than one Print Composer.
Occurs when exiting the program or loading another project file.

**Comment by manisandro** [comment] 2015-03-02 18:26
I cannot reproduce this here. What platform are you on? Can you post a sample project somewhere? Thanks.

**Comment by dysteleologist** [comment] 2015-03-02 22:37
Windows 8.1 64bit, OSGeo4W 64bit, QGIS 2.8.1
Windows 7 64bit, OSGeo4W 64bit, QGIS 2.6.1

I have reproduced the crash on both the above setups (with fresh OSGeo4W install on Win 8.1).

Sample 2.8.1 project (no layers, two print composers saved) here: https://onedrive.live.com/redir?resid=366F424924FA30F2%213916
But the crash occurs on any project as soon as there is more than one Print Composer saved within the project (composer manager).

**Comment by manisandro** [comment] 2015-03-02 23:40
Ok found out what is going on. This is a QGIS bug, see https://github.com/qgis/QGIS/pull/1938. Unfortunately I don't really see a way to completely work around the issue, the best I can do is not make it crash if the Instant Print dialog is not open (see above commit).

**Comment by manisandro** [comment] 2015-06-15 09:04
Closing since fixed in QGIS >= 2.8.2

**Closed by manisandro** 2015-06-15 09:04 UTC
